# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:6.0
COPY . /Backend
WORKDIR /Backend
RUN dotnet tool install --global dotnet-ef
RUN dotnet restore
RUN dotnet build Releases/Releases.App/Releases.App.csproj
EXPOSE 80/tcp
RUN chmod +x ./entrypoint_releases.sh
CMD /bin/bash ./entrypoint_releases.sh